{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hyperfleet-api.fullname" . }}-crd-viewer
  labels:
    {{- include "hyperfleet-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hyperfleet-api.fullname" . }}-crd-viewer
subjects:
  - kind: ServiceAccount
    name: {{ include "hyperfleet-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
