apiVersion: v2
name: hyperfleet-api
description: HyperFleet API - Cluster Lifecycle Management Service with Custom Resource Definitions for Kubernetes-native discoverability
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - api
  - kubernetes
  - cluster-management
  - crd
  - custom-resource-definition
home: https://github.com/openshift-hyperfleet/hyperfleet-api
